export const courses = [
  "Matematika",
  "Biologi",
  "Fisika",
  "Kimia",
  "Geografi",
  "Sejarah",
  "Sosiologi",
  "Ekonomi",
  "Bahasa Indonesia",
  "Bahasa Inggris",
  "Bahasa Mandarin",
  "Bahasa Jepang",
  "Seni Budaya",
  "Pendidikan Jasmani, Olah Raga, dan Kesehatan",
  "Prakarya dan Kewirausahaan",
  "Pendidikan Pancasila dan Kewarganegaraan",
  "Pendidikan Agama dan Budi Pekerti",
];
